server:
  port: "8040"
spring:
  data:
    mongodb:
      database: userdb
      host: localhost
      port: "27017"
      uri: mongodb://localhost/userdb
      username: ""
  application:
    name: UserProfile


